Firefly 708 remove selected images from viewer
Caltech-IPAC/firefly pull request #1070
Opened 2021-03-29 16:58 UTC by deannaji

Jira: https://jira.ipac.caltech.edu/browse/FIREFLY-708

Testing:
- Run a search ex: M17
- Click on "list view", instead of tiles view.
- A dialog with a table will show up, select some rows and then click "Remove Selected" button.

2021-03-29 17:54 UTC, loitly requested changes
There are several issues I find with this PR.  Please fix.

- If you sort the table, it remove the WRONG images.  The logic for mapping table's rowIdx to plotId is wrong.
- Watching for table changes is not needed, unless you want to enable/disable the `Remove` button based on whether table rows are selected.  Since, you are not doing this, you should at least show a popup when the button is clicked, but no rows were selected.
- Try disabling IntelliJ auto-format.  Over 80% of the changes in this PR is format related.  This makes it very difficult for reviewer to see the real changes.

2021-03-29 17:54 UTC, loitly commented on src/firefly/js/visualize/ui/ExpandedOptionsPopup.jsx
> +}
dead code.

2021-03-29 17:54 UTC, loitly commented on src/firefly/js/visualize/ui/ExpandedOptionsPopup.jsx
>          }
This is the correct way to watch and response to table actions.

2021-03-29 17:54 UTC, loitly commented on src/firefly/js/visualize/ui/ExpandedOptionsPopup.jsx
> +}
For what you want to do, there is no need to watch for table changes.  To get the selectInfo of a table, simply call:  `TableUtil.js:getTblInfoById`  i.e.

```
const selectInfoCls = SelectInfo.newInstance(getTblInfoById(TABLE_ID)?.selectInfo);
selectInfoCls.getSelected().forEach( (rowIdx) => {
    const plotId = convertRowIdxToPlotId(rowIdx);    // todo:  need to implement
    dispatchDeletePlotView({plotId});
});
```

2021-04-19 16:00 UTC, deannaji commented
@loitly , fixed thanks please verify

2021-04-19 17:32 UTC, ejoliet approved these changes
Looks fixed.
(i noticed that there are files that has changed but only because of reformatting - not sure we want to consider those into the PR but its minor)

2021-04-19 17:56 UTC, loitly requested changes
Again, the many formatting changes are so confusing to review.  There was only 10 or so lines of changes, but I had to browse through hundreds of lines to get there.
Also, it does not work.  Try select all, then unselect one, then remove images.  You should also try filtering and sorting the table before removing images.  Please fix, test, then resubmit PR.

2021-04-19 17:56 UTC, loitly commented on src/firefly/js/visualize/ui/ExpandedOptionsPopup.jsx
> +import {TABLE_SELECT} from '../../tables/TablesCntlr';
These are not longer used..  can be removed.

2021-04-19 17:56 UTC, loitly commented on src/firefly/js/visualize/ui/ExpandedOptionsPopup.jsx
> +}
Logic is wrong.  I pretty much wrote the code needed to get selected PlotIds in my comment on your last PR.  Did you not see it?

If you do a select all, then unselect a row before remove images.. it removes the wrong images.

2021-04-26 17:07 UTC, loitly approved these changes
You still did not use the util function I asked you to.  However, your code works and that's good enough for me.

@ejoliet I found something while testing.  You decide whether or not it's a bug. 
The image grid and the table only sync up when the table icon is clicked.  Maybe, we should reset table sort/filter if another search is added.
To duplicate:
- Image Search: m31, WISE ALLWISE Atlas    (4 images)
- bring up table, filter on `w2`
- Image Search: m31, WISE ALLWISE Atlas    (4 images added)
- bring up table, the previous filter is now applied to the image grid

2021-05-06 20:41 UTC, robyww requested changes
OK, it is all working, but it does need some code cleanup.

Also- I highlighted some stuff eslint catches. Do you have it configure with your intelliJ?

2021-05-06 20:41 UTC, robyww commented on src/firefly/js/visualize/ui/ExpandedOptionsPopup.jsx
> +        tableModel.tableData.data.map(row => !selectInfo.exceptions.has(parseInt(row[7])) ? row[2] : '')
should be `(row) =>`

2021-05-06 20:41 UTC, robyww commented on src/firefly/js/visualize/ui/ExpandedOptionsPopup.jsx
> +        Array.from(selectInfo.exceptions).map(idx =>
should be `(idx) =>`

2021-05-06 20:41 UTC, robyww commented on src/firefly/js/visualize/ui/ExpandedOptionsPopup.jsx
> +            tableModel.tableData.data[idx][2])
`;` here

2021-05-06 20:41 UTC, robyww commented on src/firefly/js/visualize/ui/ExpandedOptionsPopup.jsx
> +const [NAME_IDX, WAVE_LENGTH_UM, PID_IDX, STATUS, PROJ_TYPE_DESC, WAVE_TYPE, DATA_HELP_URL] = [0, 1, 2, 3, 4, 5, 6];
Add another constant for row id.
```js
const [NAME_IDX, WAVE_LENGTH_UM, PID_IDX, STATUS, PROJ_TYPE_DESC, WAVE_TYPE, DATA_HELP_URL,ROW_ID] = [0, 1, 2, 3, 4, 5, 6,7];

```
```

2021-05-18 16:46 UTC, robyww approved these changes

2021-05-25 22:21 UTC, merged