[DM-30073] Handle redirects when retrieving TAP errors
Caltech-IPAC/firefly pull request #1091
Opened 2021-05-13 20:30 UTC by rra

Errors from an async TAP call are stored the same way as data
results and thus may return a redirect to an external URL that
does not understand our tokens.  However, they lacked special
redirect handling and the underlying request library would resend
the authentication token for the original request when following
the redirect.  This in turn led to sending authentication tokens
to sites (such as a GCS bucket URL) which did not understand them.

Copy the same code pattern from getData to getErrorMsg: disable
redirects, check the result for a redirect status, and then follow
the redirect manually, re-checking its URL for whether we should
send an authentication token.

I suspect the status of the secondary request may not propagate
back to the outer request for both this and getData, but couldn't
confirm that.  In the longer term, we should rethink how this
code works (and possibly use an underlying HTTP library that strips
Authorization headers when following redirects).

2021-05-13 21:07 UTC, ejoliet commented
@loitly heads up - i did `gl :firefly:bAD` and it failed compiling java:
```
> Task :firefly:compileJava
/private/tmp/firefly/src/firefly/java/edu/caltech/ipac/firefly/server/query/AsyncTapQuery.java:212: error: variable method is already defined in method getErrorMsg()
                                (method -> err.setSource(getErrResp(method, errorUrl))));
```

2021-05-13 21:11 UTC, gpdf commented
@ejoliet I think this is `bug`, not `enhancement`.

2021-05-13 21:36 UTC, rra commented
Apologies for that; I don't have a Java development environment set up and was afraid of something like that. :( I'm not sure what is the correct syntactical way to express that method callback in Java for the interior call to `getData`.

2021-05-13 21:37 UTC, loitly requested changes
Logic looks good.  Please correct the compilation error, then it's good to go.

2021-05-13 21:37 UTC, loitly commented on src/firefly/java/edu/caltech/ipac/firefly/server/query/AsyncTapQuery.java
> +                                (method -> err.setSource(getErrResp(method, errorUrl))));
Fail to compile.  `method` is already declared at line 204.

2021-05-13 21:50 UTC, loitly approved these changes

2021-05-14 00:14 UTC, gpdf commented
https://jira.ipac.caltech.edu/browse/FIREFLY-780 for fixing this in the 2021.2.x series.

2021-05-14 16:06 UTC, gpdf commented
Changing the base branch did not do what I expected.

2021-05-14 16:07 UTC, gpdf commented
This PR is probably a goner at this point.  I'll work on making a new one from scratch.

2021-05-14 16:11 UTC, robyww commented
Changing the branch base is rarely a good idea. That is why I asked you to close this one and open a new one to `rc-2021.2`. We have had bad experience with changing the branch base in the past.

2021-05-14 16:20 UTC, gpdf commented
Already done: #1092

2021-05-14 16:21 UTC, gpdf commented
Closing; no longer useful.

2021-05-14 16:21 UTC, closed without merging

2021-05-14 16:23 UTC, gpdf commented
I wasn't sure that I could preserve @rra's authorship if I made a new branch from scratch, but in the end it worked out fine.