Default Spatial Target with proper Errors validation
Caltech-IPAC/firefly pull request #1118
Opened 2021-08-03 00:26 UTC by brianv0

Fixes validation issues in TAP panel, both the error messages themselves and the bubbling up of those errors.

2021-08-03 16:09 UTC, robyww commented
_test build:_ https://fireflydev.ipac.caltech.edu/u-bvan-spatial-target-and-errors/firefly/

2021-08-03 16:24 UTC, robyww commented
>  If you switch to ObsCore table (which does have an ra/dec), deselect "Spatial" Dropdown (same widget but it has a different title)

I have real concerns about this one. This will promote all-sky searches. I thought this PR was to discourage that. Am I missing something?

2021-08-03 17:17 UTC, gpdf commented
It was primarily to discourage all-sky searches on regular catalogs, but I think you're right, limited-sky-area searches should be the default for (ObsCore) image metadata tables, too.

2021-08-03 17:20 UTC, robyww requested changes
@brianv0 the code looks good and it works but I think @gpdf and I agree

> we should  limited-sky-area searches should be the default for (ObsCore) image metadata tables, too.

2021-08-03 18:19 UTC, gpdf requested changes
To complete my review after interacting with the test build:

I agree with @robyww : it seems like the behavior for ordinary spatial catalogs and for non-spatial tables is as agreed.  Thanks!

Please do change the ObsCore default to enabling spatial search, with the target field left empty (and therefore the "empty entry" error displayed as for regular spatial catalogs).

2021-08-05 04:36 UTC, brianv0 commented
Boolean has been reversed to make sure the panel is active if an ObsCore table has been selected.

2021-08-05 15:26 UTC, robyww approved these changes

2021-08-05 15:26 UTC, robyww commented
All looks good now. I will merge.

2021-08-05 15:27 UTC, merged