IRSA-4289_ztf_icon_in_the_upper_left_is_transparent
Caltech-IPAC/firefly pull request #1146
Opened 2021-11-04 04:16 UTC by deannaji

Jira: https://jira.ipac.caltech.edu/browse/IRSA-4289
K8s:

2021-11-04 16:13 UTC, loitly requested changes
These changes should not be in firefly.  Instead, for ZTF, change it here:
https://github.com/IPAC-SW/irsa-ife/blob/6f0434d02d6abe174a65083a4b9ef9dd45f9b8fe/src/irsa/js/ztf/Ztf.jsx#L27

You can do the same for other projects at its corresponding places.

2021-11-04 16:18 UTC, loitly commented on src/firefly/js/ui/Banner.css
> +    background-color: #3d3d3d;
Also, I think #3e3e3e matches the black better.

2021-11-04 16:51 UTC, robyww requested changes
This is going to affect others app beyond ZTF so we can't just change this just to make ZTF look better. In general, I don't really like the way this looks and I am concerned it will not look right in other apps.  We need to discuss exactly what the goal is.

2021-11-08 23:10 UTC, ejoliet commented
> This is going to affect others app beyond ZTF so we can't just change this just to make ZTF look better. In general, I don't really like the way this looks and I am concerned it will not look right in other apps. We need to discuss exactly what the goal is.

@deannaji What was the final proposal to improve the icon UI?

2021-11-08 23:10 UTC, ejoliet commented
(BTW, i think it looks good in any app - where is not going to fit well? TimeSeries? )

2021-11-08 23:59 UTC, robyww commented
I gave @deannaji an Icon that works well with ZTF.  It looks quite good without having to mess with any CSS layout issue.
![Screen Shot 2021-11-08 at 4 57 29 PM](https://user-images.githubusercontent.com/6730519/140836992-ea6907ce-0618-40eb-96a3-22d41089e648.png)

I think if we have icons that don't look right this is more the way to go.

2021-11-14 06:47 UTC, closed without merging