FIREFLY-1310: Prototype of Drag Drop UI for file uploads
Caltech-IPAC/firefly pull request #1426
Opened 2023-09-12 23:24 UTC by kpuriIpac

#### [Firefly-1310](https://jira.ipac.caltech.edu/browse/FIREFLY-1310)
- a simple drag drop UI for file upload
- need to consider how big to make the space for drag & drop, and what happens to it after a user uploads a file, since we immediately display the file analysis results 
   - potentially make the entire window draggable/droppable for files

**Testing**: 
- https://fireflydev.ipac.caltech.edu/firefly-1310-drag-drop-file-ui/firefly
- Go to "Upload" and test the drag and drop feature to upload a file

2023-09-12 23:43 UTC, loitly approved these changes
Good effort.  It Looks really nice.  I would move `Choose Files` and the text under it into the box like how you suggested it.  That way it's clear that it's an 'or' operation.

2023-09-12 23:43 UTC, loitly commented on src/firefly/js/ui/FileUpload.jsx
> +    const handleDrop = (e) => {
Consider using `useCallback` when passing functions to another component to avoid unnecessary re-renders.

2023-10-17 16:10 UTC, robyww requested changes
It is all working but needs some more clean up. We can go over them when you are ready.

Summary of suggestions.
- Don't modify RadioGroupInputField, control the value instead with useEffect
- Only pass dropEvent to `FileUpload` and maybe a prop to control the message.
- remove  `const [isFileDrop, setFileDrop] = useState(() => false);` altogether. Control stuff by checking the event.

2023-10-17 16:10 UTC, robyww commented on src/firefly/js/ui/FileUpload.jsx
> +        }
is approach is fine. Just don't use isFileDrop use `dropEvent`. I think you can get away with not using get/setFileDrop at all.

2023-10-17 16:10 UTC, robyww commented on src/firefly/js/ui/FileUpload.jsx
> +        setFileDrop(false);
There is probably a way to not need this line.

2023-10-17 16:10 UTC, robyww commented on src/firefly/js/visualize/ui/FileUploadViewPanel.jsx
> +                            isFileDrop={isFileDrop}
I think you can change with and use an `useEffect` and `useFieldGroupValue` to change this field and not need extra properties.

2023-10-27 16:05 UTC, robyww approved these changes
This looks good. I really appreciate you pursuing this idea. It is a major UI improvement.

 I think you can remove `setDropEvent` as a prop in `FileUpload`. Look at my two suggestions and play with that and see if you can get it to work. Either way go ahead and merge after that.

2023-10-27 23:21 UTC, merged