FIREFLY-1347: showPropertySheetButton option should be consistent with other table's options
Caltech-IPAC/firefly pull request #1448
Opened 2023-11-15 17:33 UTC by loitly

Ticket: https://jira.ipac.caltech.edu/browse/FIREFLY-1347
Also, fixes property sheet popup in API mode

Test: https://fireflydev.ipac.caltech.edu/firefly-1347-propertysheet/firefly/
and:  https://firefly-1347-propertysheet.irsakudev.ipac.caltech.edu/irsaviewer/
Ensure 'Details' tab in tri-view still works as expected.

Test: https://fireflydev.ipac.caltech.edu/firefly-1347-propertysheet/firefly/test/ 
Ensure popup button 'Show details for the selected row' work as expected.  It should show the content of the current table's highlighted row.

Test: https://firefly-1347-propertysheet.irsakudev.ipac.caltech.edu/applications/wise/
There should be a 'Details' tab on the right side that display the details of the active table highlighted row.
There should not be a 'Show details...' button on the table's toolbar.

2023-11-16 16:48 UTC, robyww commented
UI Testing: If I push the button -> keep the dialog up -> push the button on the different table then the dialogs does not update to that new table. The dialog has to be closed first.

2023-11-16 16:54 UTC, robyww requested changes
Code looks good. I found two UI issues for you to take a look at.

2023-11-16 23:56 UTC, loitly commented
> * If I push the button -> keep the dialog up -> push the button on the different table then the dialogs does not update to that new table. The dialog has to be closed first.
> * The table title should be in the dialog title: such as: `Row Details: ATLAS`

Change request added.

2023-11-17 15:42 UTC, robyww approved these changes

2023-11-17 16:54 UTC, merged