IRSA-5925: Convert Euclid to JoyUI
Caltech-IPAC/firefly pull request #1524
Opened 2024-03-28 18:40 UTC by kpuriIpac

**[IRSA-5925](https://jira.ipac.caltech.edu/browse/IRSA-5925)**: 

- IRSA PR: https://github.com/IPAC-SW/irsa-ife/pull/313
- small changes to the `EmbeddedPositionSearchPanel's` position (to make it look not stuck to the bottom left of the screen for Euclid). 
- test DCE to ensure the EmbeddedPositionSearchPanel looks good, if not, I can revert these changes. 

Testing: 
- Euclid: https://irsa-5925-euclid-joyui.irsakudev.ipac.caltech.edu/applications/euclid
- IRSAViewer (DCE): https://irsa-5925-euclid-joyui.irsakudev.ipac.caltech.edu/irsaviewer

2024-03-28 23:14 UTC, robyww requested changes
Sorry to be picky but this really is not the right way to do this. For DCE it does not improve anything.

I think we need to add a slot props approach. 

 - use a slot name called 'searchRoot'
 - then in the `sx` it should around line 180 add `...searchRoot?.props?.sx`
 - then on the Euclide side: 
 ```jsx
 slotProps= {searchRoot: {props: {sx: {bottom:'3.5rem', left:'1rem'}}}
```

2024-03-28 23:27 UTC, robyww commented
One more note... we probably need to convert other parts of this component to slotProps as well

2024-03-29 00:02 UTC, kpuriIpac commented
> Sorry to be picky but this really is not the right way to do this. For DCE it does not improve anything.
> 
> I think we need to add a slot props approach.
> 
> * use a slot name called 'searchRoot'
> * then in the `sx` it should around line 180 add `...searchRoot?.props?.sx`
> * then on the Euclide side:
> 
> ```js
> slotProps= {searchRoot: {props: {sx: {bottom:'3.5rem', left:'1rem'}}}
> ```

Not at all, that's helpful feedback! I'm considering now, though, whether to make this one change now, or take care of `slotProps` altogether in the new `EmbeddedPositionSearchPanel` ticket?

2024-03-29 00:52 UTC, jaladh-singhal commented on src/firefly/js/ui/dynamic/EmbeddedPositionSearchPanel.jsx
> +                        bottom: '3.5rem',
Oh I didn't notice this before - I made a comment about this in your ife PR. The bottom can be 2.5rem maybe: 1rem (same as left) + 1.5rem (height + y margins of mouse-readout line)

2024-04-01 16:24 UTC, loitly commented
> slotProps= {searchRoot: {props: {sx: {bottom:'3.5rem', left:'1rem'}}}

When defining `slotProps`, no need to include `props` as a property.  It is implied that the props are for the given slot.

2024-04-03 01:32 UTC, robyww approved these changes

2024-04-03 21:42 UTC, merged